### ISSUE TITLE
Problems with `Makefile`

### ISSUE THREAD

**Issue by sprintersb** [gitdode/thermidity#32]
`Makefile`
---
* Option `-D__AVR_ATmega328P__` should be removed. This is a built-in define, and provided by `specs-atmega328p` since v5. If the compiler does not work as expected without defining that macro by hand, the toolchain is broken.
* Option `-Wl,--relax` bypasses the assembler and should be replaced by `-mrelax`. Otherwise, the assembler might compute symbol values / offsets at assembly time, but which are actually not computable at assembly time because linker relaxation might change their values.
* `thermidity.elf` depends on header files like `font.h`, which is not described in the current Makefile. This means that when you only change some header(s) and then rerun `make`, it won't re-build `thermidity.elf`.

**Comment by gitdode** [comment]
- I've added `__AVR_ATmega328P__` so the Makefile based project configuration in NetBeans is also aware of the MCU. I might have to use manual configuration instead because of https://github.com/apache/netbeans/discussions/6421 and then I guess I can remove `__AVR_ATmega328P__` from the Makefile.
- Replaced `-Wl,--relax` with `-mrelax`.
- Checking how to do that...

**Comment by sprintersb** [comment]
> NetBeans is also aware of the MCU
Ah, makes sense. I don't use NetBeans. Years ago I used it with Java and the experience was very good. But I tries several times to installit on Linux but was never successful :-(

> Checking how to do that...
One way is to add a dependency without a rule:
```
$(TARGET).elf: foo.h bar.h bazz.h ... Makefile

**Comment by gitdode** [comment]
It was possible to remove `__AVR_ATmega328P__` from the Makefile and get rid of the false error markers caused by `__flash` with project configuration type 'Application' instead of 'Makefile', allowing to freely set 'Preprocessor Definitions', where I could simply add `__AVR_ATmega328P__` and `__flash=volatile` which of course is plain wrong but calms down 'Code Assistance' and all is fine in the editor. And of course the code is built with the Makefile as usual.

I like NetBeans quite a lot, it is very good in handling very large Java projects and works very well with Maven. And since it is under the roof of the Apache Software Foundation it advances very well. My colleagues all use IntelliJ but I just like to work with Open Source software :)
